version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET_KEY: "your_secret_here"
      DBHOST: db
      DBNAME: final_db
      DBUSER: final_user
      DBPASSWORD: final_pass
      SSLMODE: require
      OPENWEATHER_API_KEY: "your_api_key_here"
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: final_db
      POSTGRES_USER: final_user
      POSTGRES_PASSWORD: final_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
